apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
      - name: airflow
        image: puckel/docker-airflow
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: airflow-service
spec:
  type: NodePort
  selector:
    app: airflow
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30002

