apiVersion: v1
kind: Service
metadata:
  name: superset
spec:
  type: NodePort
  ports:
  - port: 8088
    nodePort: 30009
  selector:
    app: superset
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
spec:
  selector:
    matchLabels:
      app: superset
  replicas: 1
  template:
    metadata:
      labels:
        app: superset
    spec:
      containers:
      - name: superset
        image: amancevice/superset
        ports:
        - containerPort: 8088
        env:
        - name: SUPERSET_DB_URI
          value: "postgresql+psycopg2://superset:superset@postgres:5432/superset"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: superset-secret
              key: superset


